### Intro to NumPy

In [1]:
import numpy as np

In [8]:
# Single-dimensional array
n1 = np.array([10, 20, 30, 40])
n1

array([10, 20, 30, 40])

In [9]:
# Multi-dimensional array
n2 = np.array([[10, 20, 30, 40], [40, 30, 20, 10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [10]:
print(type(n1))
print(type(n2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
# Initializing NumPy array with zeros
n3 = np.zeros((3, 4), dtype = 'int32')
n3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [12]:
# Initializing NumPy array with same number
n4 = np.full((3, 3), 5)
n4

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
# Initializing NumPy array within a range
n5 = np.arange(10, 20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
n6 = np.arange(10, 51, 5)
n6

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
# Initializing NumPy array with random numbers
n7 = np.random.randint(1, 50, 5)
n7

array([ 1, 21,  6, 31, 47])

In [18]:
# Checking the shape of NumPy array
n8 = np.array([[1, 2, 3], [4, 5, 6]])
n8.shape

(2, 3)

In [19]:
n8.shape = (3, 2)
n8

array([[1, 2],
       [3, 4],
       [5, 6]])

### Joing NumPy Arrays

In [20]:
# vstack
n10 = np.array([10,20,30])
n11 = np.array([40,50,60])

np.vstack((n10, n11))

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
# hstack
n12 = np.array([10,20,30])
n13 = np.array([40,50,60])

np.hstack((n12, n13))

array([10, 20, 30, 40, 50, 60])

In [22]:
n14 = np.array([10,20,30])
n15 = np.array([40,50,60])

np.column_stack((n14, n15))

array([[10, 40],
       [20, 50],
       [30, 60]])

### NumPy Intersection and Difference

In [25]:
n20 = np.array([10,20,30,40,50,60])
n21 = np.array([50,60,70,80,90])

np.intersect1d(n20, n21)

array([50, 60])

In [26]:
np.setdiff1d(n20, n21)

array([10, 20, 30, 40])

In [27]:
np.setdiff1d(n21, n20)

array([70, 80, 90])

### NumPy Array Mathematics

In [28]:
# Addition of NumPy array
n22 = np.array([10,20])
n23 = np.array([30,40])

np.sum([n22, n23])

100

In [29]:
np.sum([n22, n23], axis = 0)

array([40, 60])

In [30]:
np.sum([n22, n23], axis = 1)

array([30, 70])

In [31]:
# Bais Addition
n22 = n22 + 5
n22

array([15, 25])

In [32]:
# Basic Multiplication
n23 = n23 * 2
n23

array([60, 80])

In [33]:
# Mean
np.mean(n22)

20.0

In [34]:
# Standard Deviation
np.std(n22)

5.0

In [35]:
# Median
np.median(n22)

20.0

### Saving and Loading Numpy Arrays

In [36]:
# Saving Numpy Array
n25 = np.array([10, 20, 30, 40, 50, 60])
np.save('final_numpy_array', n25)

In [37]:
n26 = np.load('final_numpy_array.npy')
n26

array([10, 20, 30, 40, 50, 60])