## Load in Numpy

In [2]:
import numpy as np

## The Baiscs

In [9]:
a = np.array([1, 2, 3], dtype = 'int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get Type
a.dtype

dtype('int16')

In [11]:
# Get Size (in bytes)
a.itemsize

2

In [12]:
# Get total size
a.nbytes

6

## Accessing/Changing specific elements, rows, columns, etc

In [13]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specific element [R, C]
a[1, 5]

13

In [15]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [18]:
# Getting more fancy[startindex:endindex;stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [19]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [20]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [21]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [22]:
# 3D Example
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
# Get a specific element(work outside in)
b[0, 1, 1]

4

In [24]:
# Replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [25]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# All 1s matrix
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [28]:
# Any other number(full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.36161637, 0.24896592],
       [0.65725776, 0.43484032],
       [0.92447159, 0.24582929],
       [0.66295732, 0.95828328]])

In [31]:
# Random integer values
np.random.randint(-4, 7, size = (3, 3))

array([[-2, -2,  1],
       [-3,  0,  5],
       [ 5,  5,  3]])

In [32]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [37]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!

In [4]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


## Mathematics

In [5]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [6]:
a + 2

array([3, 4, 5, 6])

In [7]:
a - 2

array([-1,  0,  1,  2])

In [8]:
a * 2

array([2, 4, 6, 8])

In [9]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [10]:
a * b

array([1, 0, 3, 0])

In [11]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Linear Algebra

In [12]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [13]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [14]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [17]:
stats = np.array([[1,2 ,3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.min(stats)

1

In [19]:
np.max(stats)

6

In [20]:
np.max(stats, axis=1)

array([3, 6])

In [21]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Arrays

In [22]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8, 1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [23]:
# Verticallly stacking vectors

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous
#### Load Data From File

In [29]:
filedata = np.genfromtxt('data/data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Boolean Masking and Advanced Indexing

In [31]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [32]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [34]:
# We can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [35]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [36]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])